version: '2.0'
services:
  nginx:
    build: ./nginx
    volumes:
        - ./conf.d:/etc/nginx/conf.d
    ports:
        - "3000:80"
  app:
    build: ./app
    ports:
      - "4000:80"
  ipfs:
    image: ipfs/go-ipfs:latest
    # ports:
        # - "8080:8080"
        # - "5001:5001"
    # environment:
    #     - IPFS_LOGGING=warn
